### ISSUE TITLE
COLUMN_LOCAL_FILENAME is deprecated; use ContentResolver.openFileDescriptor() instead

### ISSUE THREAD

**Issue by xiaoya1233** [chiclaim/AndroidUpdater#12]
java.lang.SecurityException: COLUMN_LOCAL_FILENAME is deprecated; use ContentResolver.openFileDescriptor() instead
	at android.app.DownloadManager$CursorTranslator.getString(DownloadManager.java:1516)
	at android.app.DownloadManager.getUriForDownloadedFile(DownloadManager.java:1106)
	at com.chiclam.android.updater.FileDownloadManager.getDownloadUri(FileDownloadManager.java:121)
	at com.chiclam.android.updater.Updater.download(Updater.java:68)
	at com.rsr.jbcat.user.update.UpdateDialog.onClick(UpdateDialog.java:129)
	at android.view.View.performClick(View.java:5664)
	at android.view.View$PerformClick.run(View.java:22436)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6343)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:920)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

提示这个  怎么解决呀

**Comment by chiclaim** [comment]
@xiaoya1233  ContentResolver#openFileDescriptor(Uri, String) 试下这个方法

**Comment by xiaoya1233** [comment]
public Uri getUriForDownloadedFile(long id) {
        // to check if the file is in cache, get its destination from the database
        Query query = new Query().setFilterById(id);
        Cursor cursor = null;
        try {
            cursor = query(query);
            if (cursor == null) {
                return null;
            }
            if (cursor.moveToFirst()) {
                int status = cursor.getInt(cursor.getColumnIndexOrThrow(COLUMN_STATUS));
                if (DownloadManager.STATUS_SUCCESSFUL == status) {
                    return ContentUris.withAppendedId(Downloads.Impl.ALL_DOWNLOADS_CONTENT_URI, id);
                }
            }
        } finally {
            if (cursor != null) {
                cursor.close();
            }
        }
        // downloaded file not found or its status is not 'successfully completed'
        return null;
    }

我在你的这个方法里没发现你使用了下面的这个COLUMN_LOCAL_FILENAME啊
   public String getString(int columnIndex) {
            final String columnName = getColumnName(columnIndex);
            switch (columnName) {
                case COLUMN_LOCAL_URI:
                    return getLocalUri();
                case COLUMN_LOCAL_FILENAME:
                    if (!mAccessFilename) {
                        throw new SecurityException(
                                "COLUMN_LOCAL_FILENAME is deprecated;"
                                        + " use ContentResolver.openFileDescriptor() instead");
                    }
                default:
                    return super.getString(columnIndex);
            }
        }
