### ISSUE TITLE
android 7.0以上 会报错

### ISSUE THREAD

**Issue by Jack-Xiao** [chiclaim/AndroidUpdater#6]
使用了与楼主类似的方式下载升级app， 然而最近发现在android7.0以上会报错（android5.1及以下没有问题，android 6.0有些有问题),希望楼主也看看是什么问题，谢过。
报错的位置在最后的context.startActivity(intent)中。
以下是报错的内容：
12-09 10:36:39.988 17634-17647/android.process.media E/DatabaseUtils: Writing exception to parcel
                                                                      java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/22 from pid=4938, uid=10026 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
                                                                          at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:608)
                                                                          at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:483)
                                                                          at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:474)
                                                                          at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:419)
                                                                          at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:313)
                                                                          at android.os.Binder.execTransact(Binder.java:565)
12-09 10:36:39.995 4938-4960/com.android.packageinstaller E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                            Process: com.android.packageinstaller, PID: 4938
                                                                            java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)
                                                                             Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/22 from pid=4938, uid=10026 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
                                                                                at android.os.Parcel.readException(Parcel.java:1684)
                                                                                at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                                at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
                                                                                at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
                                                                                at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1149)
                                                                                at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:986)
                                                                                at android.content.ContentResolver.openInputStream(ContentResolver.java:706)
                                                                                at com.android.packageinstaller.PackageInstallerActivity$StagingAsyncTask.doInBackground(PackageInstallerActivity.java:738)
                                                                                at com.android.packageinstaller.PackageInstallerActivity$StagingAsyncTask.doInBackground(PackageInstallerActivity.java:729)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                at java.lang.Thread.run(Thread.java:761)

**Comment by zhouzl18** [comment]
这个是没有授予权限，android6.0以上对危险权限需要用户授予

2016-12-09 10:38 GMT+08:00 小江 <notifications@github.com>:

**Comment by Jack-Xiao** [comment]
对的，这是缺少一个权限。
startActivity 对于android 7.0以上机型需要增加 Intent.FLAG_GRANT_READ_URI_PERMISSION 权限

**Comment by chiclaim** [comment]
@Jack-Xiao @zhouzl18 我使用华为荣耀V8 ，Android7.0的系统，并没有出现这个错误，能否告知下你有问题的机型是什么？

**Comment by dujunily** [comment]
小米5 android7.0 会在这里报错，主要原因是//本地的版本大于当前程序的版本直接安装
                        if (UpdaterUtils.compare(updaterConfig.getContext(), uri.getPath()))，后者获取path为null

**Comment by iCityMobile** [comment]
@Jack-Xiao 用此方法OK了

**Comment by cymok** [comment]
mark~thanks
